services:
  mlflow-server:
    build:
      context: ./mlflow_server
    container_name: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    environment:
      MLFLOW_TRACKING_URI: http://0.0.0.0:5000

  trainer:
    build:
      context: ./trainer
    container_name: xgboost-trainer
    depends_on:
      - mlflow-server
    network_mode: "host"
    volumes:
      - ./data:/app/data